-- Safe cleanup: removes only technical metadata generated by Excel imports.
-- Review the SELECT result before running the UPDATE.

select id, instructor_id, start_time, note
from public.slots
where note ilike '%excel-migration:%'
   or note ilike '%demo-excel-import%'
   or note ilike '%instructor-schedule.xlsx%'
   or note ilike '%excel-import|%'
   or note ilike '%demo-sheet-import:%'
order by start_time;

-- Run only after reviewing the rows above:
--
-- update public.slots
-- set note = null
-- where note ilike '%excel-migration:%'
--    or note ilike '%demo-excel-import%'
--    or note ilike '%instructor-schedule.xlsx%'
--    or note ilike '%excel-import|%'
--    or note ilike '%demo-sheet-import:%';
